"""Update message table

Revision ID: 118cb57d351d
Revises: b21d8f66edff
Create Date: 2025-07-04 21:41:35.797160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118cb57d351d'
down_revision = 'b21d8f66edff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
