"""Se añadio una columna de password 3

Revision ID: c78ebb5aa1d9
Revises: 3d5b6b57448c
Create Date: 2025-07-03 19:05:18.569411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78ebb5aa1d9'
down_revision = '3d5b6b57448c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password3', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password3')

    # ### end Alembic commands ###
